name: 'SWM GitHub Actions Basic'

on: push

env:
  WORKFLOW_LEVEL: "This value comes from the WORKFLOW level"

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    env:
      JOB_LEVEL: "This value comes from the JOB level"

    steps:
    - name: Say Hello World
      shell: bash
      run: |
        echo "Hello World"

    - name: Check environment variables 1
      shell: bash
      env:
        STEP_LEVEL_1: "This value comes from the STEP level 1"
      run: |
        echo "workflow level: $WORKFLOW_LEVEL"
        echo "job level: $JOB_LEVEL"
        echo "step level 1: $STEP_LEVEL_1"
        echo "step level 2: $STEP_LEVEL_2"
        echo "step level 3: $STEP_LEVEL_3"

    - name: Check environment variables 2
      shell: pwsh
      env:
        STEP_LEVEL_2: "This value comes from the STEP level 2"
      run: |
        echo "workflow level: $env:WORKFLOW_LEVEL"
        echo "job level: $env:JOB_LEVEL"
        echo "step level 1: $env:STEP_LEVEL_1"
        echo "step level 2: $env:STEP_LEVEL_2"
        echo "step level 3: $env:STEP_LEVEL_3"

    - name: Check environment variables 3
      shell: bash
      env:
        STEP_LEVEL_3: "This value comes from the STEP level 3"
      run: |
        echo "workflow level: ${{ env.WORKFLOW_LEVEL }}"
        echo "job level: ${{ env.JOB_LEVEL }}"
        echo "step level 1: ${{ env.STEP_LEVEL_1 }}"
        echo "step level 2: ${{ env.STEP_LEVEL_2 }}"
        echo "step level 3: ${{ env.STEP_LEVEL_3 }}"