name: 'SWM GitHub Actions Basic'

on: push

jobs:
  build-test:
    name: 'Build & Test'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Send a message to Webex Space
      shell: bash

      run: |
        cur -X POST https://webexapis.com/v1/messages \
          -H "Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}" \
          -H "Content-type: application/json" \
          -d "{
            "roomId": "${{ secrets.WEBEX_ROOMID }}",
            "text": "메시지입니다 - FROM GITHUB 액션"
          }"

  