name: 'SWM GitHub Actions Basic'

on: push

jobs:
  build-test:
    name: 'Build & Test'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout codes
      uses: actions/checkout@v3

    - name: Send a message to Webex Space
      shell: bash

      run: |
        curl --location --request POST 'https://webexapis.com/v1/messages' \
          --header 'Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}' \
          --header 'Content-type: application/json' \
          --data-raw '{
            "roomId": "${{ secrets.WEBEX_ROOMID }}",
            "text": "메시지입니다 - FROM GITHUB 액션"
          }'

    - name: Post Message to Webex Room
      uses: chrivand/action-webex-js@main
      env:
        WEBEX_TOKEN: ${{ secrets.WEBEX_TOKEN }}
        WEBEX_ROOM_ID: ${{ secrets.WEBEX_ROOMID }}
        MARKDOWN_MESSAGE: "**Hello, world! You just ran an action from ${{ github.repository }}.**"

    - name: Send message from custom action to Webex
      uses: ./
      with:
        webexToken: ${{ secrets.WEBEX_TOKEN }}
        webexRoomId: ${{ secrets.WEBEX_ROOMID }}
        bodyText: 'Message sent by Github Actions from ${{ github.repository }}'
        bodyMarkdown: '**Hello, world! You just ran an action from ${{ github.repository }}.**'