name: 'SWM GitHub Actions Basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL VALUE'

jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest']
        nodejs: [ '16', '18' ]

    runs-on: ${{ matrix.os }}

    env:
      JOB_LEVEL_1: 'JOB LEVEL VALUE 1'

    steps:
    - name: Say Hello World 1 - ${{ matrix.os }}
      shell: bash

      run: |
        echo "OS: ${{ matrix.os }}"
        echo "nodejs version: ${{ matrix.nodejs }}"

    steps:
    - name: Say Hello World 2 - ${{ matrix.os }}
      if: matrix.os != 'windows-latest'
      shell: bash

      run: |
        echo "OS: ${{ matrix.os }}"
        echo "nodejs version: ${{ matrix.nodejs }}"