name: 'SWM GitHub Actions Basic'

on: push

jobs:
  build-test:
    name: 'Build & Test'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1
      shell: bash

      run: |
        echo "Hello World"

  deploy-dev:
    name: 'Deploy to dev'

    needs:
      - build-test
    
    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1
      shell: bash

      run: |
        echo "Hello World"

  deploy-staging1:
    name: 'Deploy to staging 1'

    needs:
      - deploy-dev
    
    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1
      shell: bash

      run: |
        echo "Hello World"

  deploy-staging2:
    name: 'Deploy to staging 2'

    needs:
      - deploy-dev
    
    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1
      shell: bash

      run: |
        echo "Hello World"

  deploy-prod:
    name: 'Deploy to prod'

    needs:
      - deploy-staging1
      - deploy-staging2
    
    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1
      shell: bash

      run: |
        echo "Hello World"