name: 'SWM GitHub Actions Basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL VALUE'

jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}

    env:
      JOB_LEVEL_1: 'JOB LEVEL VALUE 1'

    steps:
    - name: Say Hello World 1
      shell: bash

      run: |
        echo "OS: ${{ matrix.os }}"